// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gammaDynamic
List gammaDynamic(NumericVector y, double a0, double b0, double w);
RcppExport SEXP _fable_intermittent_gammaDynamic(SEXP ySEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(gammaDynamic(y, a0, b0, w));
    return rcpp_result_gen;
END_RCPP
}
// betaDynamic
List betaDynamic(NumericVector y, double v, double a0, double b0, double w);
RcppExport SEXP _fable_intermittent_betaDynamic(SEXP ySEXP, SEXP vSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(betaDynamic(y, v, a0, b0, w));
    return rcpp_result_gen;
END_RCPP
}
// gasFilterPois
List gasFilterPois(NumericVector y, double psi0, double phi, double rho, double xi0, double k, int period);
RcppExport SEXP _fable_intermittent_gasFilterPois(SEXP ySEXP, SEXP psi0SEXP, SEXP phiSEXP, SEXP rhoSEXP, SEXP xi0SEXP, SEXP kSEXP, SEXP periodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type psi0(psi0SEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type xi0(xi0SEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type period(periodSEXP);
    rcpp_result_gen = Rcpp::wrap(gasFilterPois(y, psi0, phi, rho, xi0, k, period));
    return rcpp_result_gen;
END_RCPP
}
// gasFilterNbinom
List gasFilterNbinom(NumericVector y, double psi0, double phi, double rho, double xi0, double k, int period, double alpha);
RcppExport SEXP _fable_intermittent_gasFilterNbinom(SEXP ySEXP, SEXP psi0SEXP, SEXP phiSEXP, SEXP rhoSEXP, SEXP xi0SEXP, SEXP kSEXP, SEXP periodSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type psi0(psi0SEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type xi0(xi0SEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type period(periodSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(gasFilterNbinom(y, psi0, phi, rho, xi0, k, period, alpha));
    return rcpp_result_gen;
END_RCPP
}
// gasFilterBern
List gasFilterBern(NumericVector y, double psi0, double phi, double rho, double xi0, double k, int period);
RcppExport SEXP _fable_intermittent_gasFilterBern(SEXP ySEXP, SEXP psi0SEXP, SEXP phiSEXP, SEXP rhoSEXP, SEXP xi0SEXP, SEXP kSEXP, SEXP periodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type psi0(psi0SEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type xi0(xi0SEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type period(periodSEXP);
    rcpp_result_gen = Rcpp::wrap(gasFilterBern(y, psi0, phi, rho, xi0, k, period));
    return rcpp_result_gen;
END_RCPP
}
// dampedSES
NumericVector dampedSES(NumericVector y, double mu0, double alpha, double phi);
RcppExport SEXP _fable_intermittent_dampedSES(SEXP ySEXP, SEXP mu0SEXP, SEXP alphaSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type mu0(mu0SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(dampedSES(y, mu0, alpha, phi));
    return rcpp_result_gen;
END_RCPP
}
// tweedieDensity
arma::vec tweedieDensity(arma::vec x, arma::vec mean, arma::vec dispersion, arma::vec power, bool log);
RcppExport SEXP _fable_intermittent_tweedieDensity(SEXP xSEXP, SEXP meanSEXP, SEXP dispersionSEXP, SEXP powerSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type power(powerSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(tweedieDensity(x, mean, dispersion, power, log));
    return rcpp_result_gen;
END_RCPP
}
// tweedieCDF
arma::vec tweedieCDF(arma::vec x, arma::vec mean, arma::vec dispersion, arma::vec power);
RcppExport SEXP _fable_intermittent_tweedieCDF(SEXP xSEXP, SEXP meanSEXP, SEXP dispersionSEXP, SEXP powerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type power(powerSEXP);
    rcpp_result_gen = Rcpp::wrap(tweedieCDF(x, mean, dispersion, power));
    return rcpp_result_gen;
END_RCPP
}
// tweedieInvCDF
arma::vec tweedieInvCDF(arma::vec q, arma::vec mean, arma::vec dispersion, arma::vec power);
RcppExport SEXP _fable_intermittent_tweedieInvCDF(SEXP qSEXP, SEXP meanSEXP, SEXP dispersionSEXP, SEXP powerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type q(qSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type power(powerSEXP);
    rcpp_result_gen = Rcpp::wrap(tweedieInvCDF(q, mean, dispersion, power));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fable_intermittent_gammaDynamic", (DL_FUNC) &_fable_intermittent_gammaDynamic, 4},
    {"_fable_intermittent_betaDynamic", (DL_FUNC) &_fable_intermittent_betaDynamic, 5},
    {"_fable_intermittent_gasFilterPois", (DL_FUNC) &_fable_intermittent_gasFilterPois, 7},
    {"_fable_intermittent_gasFilterNbinom", (DL_FUNC) &_fable_intermittent_gasFilterNbinom, 8},
    {"_fable_intermittent_gasFilterBern", (DL_FUNC) &_fable_intermittent_gasFilterBern, 7},
    {"_fable_intermittent_dampedSES", (DL_FUNC) &_fable_intermittent_dampedSES, 4},
    {"_fable_intermittent_tweedieDensity", (DL_FUNC) &_fable_intermittent_tweedieDensity, 5},
    {"_fable_intermittent_tweedieCDF", (DL_FUNC) &_fable_intermittent_tweedieCDF, 4},
    {"_fable_intermittent_tweedieInvCDF", (DL_FUNC) &_fable_intermittent_tweedieInvCDF, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_fable_intermittent(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
